 version: 2 
 
sources: 
  - name: airbnb 
    schema: raw 
    tables: 
      - name: listings 
        identifier: raw_listings 
        description: Contains the raw data of Airbnb listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"
 
      - name: hosts 
        description: Contains the raw data of Airbnb hosts
        identifier: raw_hosts 
 
      - name: reviews 
        description: Contains the raw data of Airbnb reviews
        identifier: raw_reviews 
        loaded_at_field: date 
        freshness:
          warn_after: {count: 1, period: hour}
          warn_after: {count: 24, period: hour}
